"""Add pgvector support and invoice embeddings

Revision ID: 4eac7fa08cfa
Revises: 8fa9e4d52bc7
Create Date: 2025-04-05 22:11:32.044929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4eac7fa08cfa'
down_revision = '8fa9e4d52bc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('embedding_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'embedding_type', name='uix_invoice_embedding_type')
    )
    op.create_index(op.f('ix_invoice_embeddings_invoice_id'), 'invoice_embeddings', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_embeddings_user_id'), 'invoice_embeddings', ['user_id'], unique=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               nullable=True)
    op.add_column('invoices', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('file_url', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('file_content_type', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('raw_data', sa.JSON(), nullable=True))
    op.alter_column('invoices', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('invoices', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('invoices', 'status')
    op.drop_column('invoices', 'due_date')
    op.add_column('items', sa.Column('item_category', sa.String(length=50), nullable=True))
    op.add_column('items', sa.Column('item_code', sa.String(length=50), nullable=True))
    op.alter_column('items', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('items', 'invoice_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('items', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('items', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('items', 'description_embedding',
               existing_type=sa.TEXT(),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=True)
    op.create_index(op.f('ix_items_invoice_id'), 'items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_items_item_category'), 'items', ['item_category'], unique=False)
    op.add_column('media', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('media', sa.Column('file_url', sa.String(length=255), nullable=False))
    op.add_column('media', sa.Column('content_type', sa.String(length=50), nullable=False))
    op.add_column('media', sa.Column('file_type', sa.Enum('image', 'pdf', 'excel', 'word', 'text', 'other', name='filetype'), nullable=True))
    op.add_column('media', sa.Column('status', sa.Enum('uploaded', 'processed', 'error', name='filestatus'), nullable=True))
    op.add_column('media', sa.Column('ocr_text', sa.Text(), nullable=True))
    op.add_column('media', sa.Column('processing_metadata', sa.JSON(), nullable=True))
    op.add_column('media', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('media', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('media', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('media', 'invoice_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('media', 'file_path',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('media', 'mime_type')
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('usage', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('usage', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('whatsapp_messages', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('whatsapp_messages', 'message_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_messages', 'message_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('whatsapp_messages', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('usage', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('usage', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('media', sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('media', 'file_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.alter_column('media', 'invoice_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('media', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('media', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('media', 'updated_at')
    op.drop_column('media', 'processing_metadata')
    op.drop_column('media', 'ocr_text')
    op.drop_column('media', 'status')
    op.drop_column('media', 'file_type')
    op.drop_column('media', 'content_type')
    op.drop_column('media', 'file_url')
    op.drop_column('media', 'original_filename')
    op.drop_index(op.f('ix_items_item_category'), table_name='items')
    op.drop_index(op.f('ix_items_invoice_id'), table_name='items')
    op.alter_column('items', 'description_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('items', 'total_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('items', 'unit_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('items', 'quantity',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('items', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('items', 'invoice_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('items', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('items', 'item_code')
    op.drop_column('items', 'item_category')
    op.add_column('invoices', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('invoices', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('invoices', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('invoices', 'raw_data')
    op.drop_column('invoices', 'file_content_type')
    op.drop_column('invoices', 'file_url')
    op.drop_column('invoices', 'tax_amount')
    op.alter_column('conversations', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_invoice_embeddings_user_id'), table_name='invoice_embeddings')
    op.drop_index(op.f('ix_invoice_embeddings_invoice_id'), table_name='invoice_embeddings')
    op.drop_table('invoice_embeddings')
    # ### end Alembic commands ### 